AgileDiary/AgileDiary/Models/DbModels/Week.cs
using System;
using System.Collections.Generic;

namespace AgileDiary.Models
{
    public class Week
    {
        public Guid WeekId { get; set; }
        public DateTime StartDate { get; set; }
        public WeekConclusion WeekConclusion { get; set; }
        public List<TopPriority> TopPriorities { get; set; }
        public List<Task> Tasks { get; set; }

        public Guid SprintId { get; set; }
        public Sprint Sprint { get; set; }
    }
}

AgileDiary/AgileDiary/Models/PageModels/Weeks/EditWeekPageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using AgileDiary.Data;
using AgileDiary.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using AgileDiary.Helpers.Mappers;
using Microsoft.EntityFrameworkCore;

namespace AgileDiary.Models.PageModels.Weeks
{
    [Authorize]
    public class EditWeekPageModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        public EditWeekPageModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public WeekViewModel Week { get; set; }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            var weekFromDb = _context.Week.Include(w => w.Tasks).FirstOrDefault(w => w.WeekId.Equals(Week.Id));
            if (weekFromDb == null)
            {
                return RedirectToPage("Index");
            }
            weekFromDb = Week.Map();
            _context.SaveChanges();
            var newUrl = Url.Page("Edit", new { weekId = Week.Id });
            return Redirect(newUrl);
        }

        public IActionResult OnGet(string weekId)
        {
            var guidGoalId = new Guid(weekId);
            Week = _context.Week.Where(w => w.WeekId.Equals(guidGoalId)).Include(w => w.Tasks).Select(w => w.Map()).FirstOrDefault();
            return Page();
        }

        public IActionResult OnGetTask(string weekId, DateTime date)
        {
            var weekFromDb = _context.Week.Include(w => w.Tasks).FirstOrDefault(w => w.WeekId.Equals(new Guid(weekId)));
            weekFromDb.Tasks.Add(new Task
            {
                TaskId = Guid.NewGuid(),
                Date = date,
                Title = "Default task title",
                Description = "Default task description"
            });
            _context.SaveChanges();
            var newUrl = Url.Page("Edit", new { weekId = weekId });
            return Redirect(newUrl);
        }
    }
}

AgileDiary/AgileDiary/Models/PageModels/Weeks/SprintWeekPageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using AgileDiary.Data;
using AgileDiary.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using AgileDiary.Helpers.Mappers;

namespace AgileDiary.Models.PageModels.Weeks
{
    [Authorize]
    public class SprintWeeksPageModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        public SprintWeeksPageModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public List<WeekViewModel> Weeks { get; set; }
        [BindProperty]
        public Guid SprintId { get; set; }

        public void OnGet(string sprintId)
        {
            var guidSprintId = new Guid(sprintId);
            Weeks = _context.Week.Where(w => w.SprintId.Equals(guidSprintId)).Select(w => w.Map()).OrderBy(w => w.StartDate).ToList();
            SprintId = guidSprintId;
        }
    }
}

AgileDiary/AgileDiary/Models/ViewModels/WeekViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgileDiary.Models.ViewModels
{
    public class WeekViewModel
    {
        public Guid Id { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public ConclusionViewModel Conclusion { get; set; }
        public List<TopPriorityViewModel> TopPriorities { get; set; }
        public List<DayViewModel> Days { get; set; }

        public Guid SprintId { get; set; }
    }
}

AgileDiary/AgileDiary/Pages/Weeks/Edit.cshtml
@page
@model AgileDiary.Models.PageModels.Weeks.EditWeekPageModel
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit week</h2>
@foreach(var day in Model.Week.Days)
{
    var taskData = new Dictionary<string, string>
    {
        { "weekId", Model.Week.Id.ToString() },
        //todo: What the fuck with format?!
        { "date", @day.Date.ToString("MM.dd.yyyy") }
    };
    <h4><b>@day.Date.ToShortDateString()</b> <a asp-page-handler="Task" asp-all-route-data="taskData">Add task</a></h4>
      
    if (@day.Tasks != null)
    {
        <ul>
            @foreach(var task in @day.Tasks)
            {
            var taskId = new Dictionary<string, string>
            {
                { "taskId", task.Id.ToString() }
            };
                <li><a asp-page="/Tasks/Edit" asp-all-route-data="taskId">@task.Title</a></li>
            }
        </ul>
    }
}

@{
        var sprintData = new Dictionary<string, string>
            {
                { "sprintId", Model.Week.SprintId.ToString() }
            };
}
<div>
    <a asp-page="SprintWeeks" asp-all-route-data="sprintData">Back to Weeks List</a>
</div>

AgileDiary/AgileDiary/Pages/Weeks/SprintWeeks.cshtml
@page
@model AgileDiary.Models.PageModels.Weeks.SprintWeeksPageModel
@{
    ViewData["Title"] = "Sprint weeks";
}

<h3>Weeks for sprint @Model.SprintId</h3>
<p>
    @{
        var sprintId = new Dictionary<string, string>
    {
                { "sprintId", @Model.SprintId.ToString() }
            };
    }
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Weeks.FirstOrDefault().StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weeks.FirstOrDefault().EndDate)
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var week in Model.Weeks)
        {
            var goalId = new Dictionary<string, string>
    {
                { "weekId", week.Id.ToString() }
            };
            <tr>
                <td>
                    @week.StartDate.ToShortDateString()
                </td>
                <td>
                    @week.EndDate.ToShortDateString()
                </td>
                <td>
                    <a asp-page="Edit" asp-all-route-data="goalId">Edit</a>
                </td>
            </tr>
        }
</table>
<div>
    <a asp-page="/Sprints/Edit" asp-all-route-data="sprintId">Back to sprint</a>
</div>