AgileDiary/Models/AgileDiaryViewModels/AllGoalsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AgileDiary.Models.Db;

namespace AgileDiary.Models.AgileDiaryViewModels
{
    public class AllGoalsViewModel
    {
        public IEnumerable<Guid> Goals { get; set; }
    }
}

AgileDiary/Models/AgileDiaryViewModels/AllSprintsViewModel.cs
using System;
using System.Collections.Generic;

namespace AgileDiary.Models.AgileDiaryViewModels
{
    public class AllSprintsViewModel
    {
        public IEnumerable<Guid> Sprints { get; set; }
    }
}

AgileDiary/Models/AgileDiaryViewModels/ConcreteGoalViewModel.cs
using AgileDiary.Models.Db;

namespace AgileDiary.Models.AgileDiaryViewModels
{
    public class ConcreteGoalViewModel : Goal
    {
    }
}

AgileDiary/Models/AgileDiaryViewModels/ConcreteSprintViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AgileDiary.Models.Db;

namespace AgileDiary.Models.AgileDiaryViewModels
{
    public class ConcreteSprintViewModel : Sprint
    {
    }
}

AgileDiary/Controllers/AgileDiary/GoalController.cs
using System;
using AgileDiary.Interfaces;
using AgileDiary.Models.AgileDiaryViewModels;
using AgileDiary.Models.Db;
using Microsoft.AspNetCore.Mvc;

namespace AgileDiary.Controllers.AgileDiary
{
    public class GoalController : Controller
    {
        private readonly ICrud<Goal> _goalService;
        public GoalController(ICrud<Goal> goalService)
        {
            _goalService = goalService;
        }

        [HttpGet]
        [Route("Goal")]
        public IActionResult Index()
        {
            var model = new AllGoalsViewModel
            {
                Goals = _goalService.ListAll()
            };
            return View("AllGoalsViewModel", model);
        }

        [HttpGet]
        [Route("Goal/{goalId}")]
        public IActionResult ConcreteGoal(Guid goalId)
        {
            var goal = _goalService.Get(goalId);
            var model = new ConcreteGoalViewModel
            {
                Id = goal.Id,
                Sprint = goal.Sprint,
                Description = goal.Description,
                Milestone = goal.Milestone,
                Result = goal.Result,
                Reason = goal.Reason,
                SprintNavigation = goal.SprintNavigation
            };
            return View(model);
        }

        [HttpPost]
        [Route("Goal/{sprintId}")]
        public IActionResult CreateGoal(Guid sprintId)
        {
            var newGoalId = _goalService.Create(sprintId);
            return Ok(newGoalId);
        }
    }
}

AgileDiary/Controllers/AgileDiary/HabitController.cs
using System;
using AgileDiary.Interfaces;
using AgileDiary.Models.Db;
using Microsoft.AspNetCore.Mvc;

namespace AgileDiary.Controllers.AgileDiary
{
    public class HabitController : Controller
    {
        private readonly ICrud<Habbit> _habitServcie;

        public HabitController(ICrud<Habbit> habitService)
        {
            _habitServcie = habitService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetHabit(Guid id)
        {
            var goal = _habitServcie.Get(id);
            return View();
        }
    }
}

AgileDiary/Views/Goal/AllGoalsViewModel.cshtml
@using AgileDiary.Models.AgileDiaryViewModels
@model AllGoalsViewModel

@{
    ViewData["Title"] = "Manage your sprints";
}

<div>
    <table class="table table-hover">
        <thead>
        <tr>
            <td>SprintId</td>
        </tr>
        </thead>

        @foreach (var goalId in Model.Goals)
        {
            <tr>
                <td>
                    <input type="checkbox" name="@goalId" value="false" class="done-checkbox" />
                </td>
                <td><a asp-controller="Goal" asp-action="ConcreteGoal" asp-route-id="@goalId">@goalId</a></td>
            </tr>
        }
    </table>

    <div class="panel-footer add-sprint add-item">
            <button type="button" id="add-sprint-button">Add</button>
    </div>
</div>

AgileDiary/Views/Goal/ConcreteGoal.cshtml
@using AgileDiary.Models.AgileDiaryViewModels
@model ConcreteGoalViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GoalEditor</title>
</head>
<body>
    <h2>@Model.Description</h2>
    <h4>Reason</h4>
    <div>@Model.Reason</div>
    <div class="panel-footer edit-button-block">
        <button type="button" id="add-goal-reason-button">Add</button>
        <button type="button" id="edit-goal-reason-button">Edit</button>
    </div>
    <h4>Result</h4>
    <div>@Model.Result</div>
    <div class="panel-footer edit-button-block">
        <button type="button" id="add-goal-result-button">Add</button>
        <button type="button" id="edit-goal-result-button">Edit</button>
    </div>
</body>
</html>

AgileDiary/Views/Sprint/ConcreteSprint.cshtml
@using AgileDiary.Models.AgileDiaryViewModels
@model ConcreteSprintViewModel
@{
    Layout = null;
}

@*<environment exclude="Development">
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/AgileDiary/Goal.min.js" asp-append-version="true"></script>
</environment>*@

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/AgileDiary/Goal.min.js" asp-append-version="true"></script>
    <title>SprintEditor</title>
</head>
<body>
    <h2>@Model.Id</h2>
    <h4>Goals</h4>
    <ul>
        @foreach (var goal in Model.Goal)
        {
            <li><a asp-controller="Goal" asp-action="ConcreteGoal" asp-route-id="@goal.Id">@goal.Description</a></li>
        }
    </ul>
    <div class="panel-footer add-goal add-item">
        <button type="button" id="add-goal-button">Add</button>
    </div>
    <h4>Habbits</h4>
    <ul>
        @foreach (var habbit in Model.Habbit)
        {
            <li><a asp-controller="Habit" asp-action="GetHabit" asp-route-id="@habbit.Id">@habbit.Id</a></li>
        }
    </ul>
    <div class="panel-footer add-habit add-item">
        <button type="button" id="add-habit-button">Add</button>
    </div>
    <h4>Weeks</h4>
    <ul>
        <li><a href="Previous Week">Previous Week</a></li>
        <li><a href="Current Week">Current Week</a></li>
        <li><a href="Next Week">Next Week</a></li>
    </ul>
    <h4>Reward</h4>
    <p style="padding-left: 30px;">@Model.Reward</p>
    <h4>Conclusion</h4>
    <p style="padding-left: 30px;">Conclusion text</p>
    <h4>Thanks</h4>
    <p style="padding-left: 30px;">Thnaks text</p>
    <h4>Improvements</h4>
    <p style="padding-left: 30px;">Improvments text</p>
    <p style="padding-left: 30px;">&nbsp;</p>
</body>
</html>

AgileDiary/Views/Sprint/SprintEditor.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SprintEditor</title>
</head>
<body>
    <h2>SprintId</h2>
    <h4>Goals</h4>
    <ul>
        <li><a title="Goal 1" href="Goal 1">Goal 1</a></li>
        <li><a title="Goal 1" href="Goal 1">Goal 1</a></li>
        <li><a title="Goal 1" href="Goal 1">Goal 1</a></li>
    </ul>
    <h4>Habbits</h4>
    <ul>
        <li><a title="Habbit1" href="Habbit1">Habbit1</a></li>
        <li><a title="Habbit1" href="Habbit1">Habbit1</a></li>
        <li><a title="Habbit1" href="Habbit1">Habbit1</a></li>
        <li><a title="Habbit1" href="Habbit1">Habbit1</a></li>
        <li><a title="Habbit1" href="Habbit1">Habbit1</a></li>
    </ul>
    <h4>Weeks</h4>
    <ul>
        <li><a href="Previous Week">Previous Week</a></li>
        <li><a href="Current Week">Current Week</a></li>
        <li><a href="Next Week">Next Week</a></li>
    </ul>
    <h4>Reward</h4>
    <p style="padding-left: 30px;">Reward text</p>
    <h4>Conclusion</h4>
    <p style="padding-left: 30px;">Conclusion text</p>
    <h4>Thanks</h4>
    <p style="padding-left: 30px;">Thnaks text</p>
    <h4>Improvements</h4>
    <p style="padding-left: 30px;">Improvments text</p>
    <p style="padding-left: 30px;">&nbsp;</p>
</body>
</html>